name: zenwealth
services:
  zenwealth-web:
    container_name: web
    build:
      context: .
      dockerfile: ZenWealth.Web/Dockerfile

    depends_on:
      - zenwealth-api

  zenwealth-api:
    container_name: api
    build:
      context: .
      dockerfile: ZenWealth.Api/Dockerfile

    depends_on:
      zenwealth-db:
        condition: service_healthy

  zenwealth-db:
    container_name: db
    image: postgres:18
    environment:
      POSTGRES_USER: zenwealth_app
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: zenwealth
    volumes:
      - pgdata:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U zenwealth_app -d zenwealth"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata: